# Use the official Node.js 20 image as the base image
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Build the TypeScript code and the Vite project
RUN npm run build

# Expose the port the app will run on
EXPOSE 3000
EXPOSE 4173

# Command to start the Vite preview server with --host
CMD ["npm", "run", "preview", "--", "--host"]
