# [build]
#   publish = "public"
#   command = "hugo --gc --minify --enableGitInfo --ignoreCache --destination=\"public/\""

# [build.environment]
#   HUGO_VERSION = "0.81.0"

# [dev]
#   command = "hugo server -D --bind 0.0.0.0 --baseURL=http://localhost:8000/"

# [[plugins]]
#   package = "netlify-plugin-hugo-cache"

# [[plugins]]
#   package = "netlify-plugin-cache-next-build"

# [[plugins]]
#   package = "netlify-plugin-inline-functions-env"
