backend:
  name: git-gateway
  branch: build

media_folder: static/images/blog
public_folder: /images/blog
repo: https://github.com/1-Power/Shafiq-Law-Chamber # Path to your GitHub repository
open_authoring: true
search: true

collections:
  - name: "blog"
    label: "Blog"
    label_singular: "Post"
    folder: "/posts"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post.template"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author Name", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "URL", name: "URL", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

